import "@/styles/globals.css";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { ToggleTheme } from "./components/ToggleTheme";
import { Notifications as MantineNotifications } from "@mantine/notifications";
import { ClerkProvider, UserButton, auth } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId }: { userId: string | null } = auth();
  const isAdmin = userId === "user_2YDD0lITApfj6aNr8KN3TbSgHaz";

  return (
    <ClerkProvider>
      <html lang="ja">
        <head>
          <ColorSchemeScript defaultColorScheme="dark" />
        </head>
        <body className={inter.className}>
          <MantineProvider defaultColorScheme="dark">
            <MantineNotifications />
            <header className="flex justify-between items-center py-3 px-4 border-b h-16">
              <div className="flex items-end gap-4">
                <Link className="font-bold text-2xl group" href="/">
                  <h1>
                    <span className="group-hover:hidden">😋 </span>
                    <span className="group-hover:inline hidden">🎃 </span>
                    BOOK^NOB 📚
                  </h1>
                </Link>
                <div className="space-x-4 font-bold">
                  <Link
                    className="hover:-translate-y-[2px] inline-block"
                    href="/"
                  >
                    Home
                  </Link>
                  <Link
                    className="hover:-translate-y-[2px] inline-block"
                    href="/books"
                  >
                    Books
                  </Link>
                  <Link
                    className="hover:-translate-y-[2px] inline-block"
                    href="/books/new"
                  >
                    Add Book
                  </Link>
                  {isAdmin && (
                    <div className="inline-flex space-x-4">
                      <div className="pl-4 border-l">
                        <span className="opacity-60 font-normal">Admin</span>
                      </div>
                      <Link
                        className="hover:-translate-y-[2px] inline-block"
                        href="/admin/categories"
                      >
                        Categories
                      </Link>
                      <Link
                        className="hover:-translate-y-[2px] inline-block"
                        href="/admin/books"
                      >
                        Books
                      </Link>
                    </div>
                  )}
                </div>
              </div>
              <div className="flex gap-4 items-center">
                {userId ? (
                  <UserButton afterSignOutUrl="/" />
                ) : (
                  <Link className="inline-block font-bold" href="/login">
                    Sign Up / Login
                  </Link>
                )}
                <ToggleTheme />
              </div>
            </header>

            <main className="p-8 h-[calc(100vh-96px)]">{children}</main>

            <footer className="grid place-content-center font-bold border-t h-8 ">
              © progLearning
            </footer>
          </MantineProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
