import '@/styles/globals.css';
import '@mantine/core/styles.css';

import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import Link from 'next/link';
import {ColorSchemeScript, MantineProvider} from '@mantine/core';
import {ToggleTheme} from './components/ToggleTheme';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='ja'>
      <head>
        <ColorSchemeScript defaultColorScheme='dark' />
      </head>
      <body className={inter.className}>
        <MantineProvider defaultColorScheme='dark'>
          <header className='flex items-end gap-4'>
            <h1 className='font-bold text-3xl'>BOOK^NOB</h1>
            <div className='space-x-4'>
              <Link href='/'>Home</Link>
              <Link href='/books'>Books</Link>
            </div>
            <ToggleTheme />
          </header>
          <main className='p-12'>{children}</main>
          <footer className='text-center'>progLearning</footer>
        </MantineProvider>
      </body>
    </html>
  );
}
